export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const GET_PRODUCTLIST = 'GET_PRODUCTLIST';
export const GET_PRODUCTSLIST_UNFILTERED = 'GET_PRODUCTSLIST_UNFILTERED';
export const GET_FB_PRODUCTS = 'GET_FB_PRODUCTS';